### ISSUE TITLE
wrong number of arguments (3 for 2) for api.send

### ISSUE THREAD

**Issue by shazadmaved** [deeproot/msg91ruby#3]
require 'msg91ruby'
    api = Msg91ruby::API.new("xxxxxxxxxxxxxxxxx","xxxxxx")
    api.send( @user.mobile, "Hello! Welcome to Your Bottle Brand! your password is #{@user.password}", 4)

The send method accepts only two parameters  -- mobile no and message and sends a promotional message but I  want to mention a transactional route with the third parameter. It throws the error wrong number of arguments (3 for 2)

**Comment by RajeshReddyM** [comment]
@shazadmaved Thank you for pointing this out. The latest version of this gem is published to ruby gems now. Bundle install now. Make sure ur gem file is referring to the latest version which is 1.0.2
